swagger: "2.0"
info:
  description: ""
  version: "0.1.0"
  title: "Auction Price Tracker API"
host: "auction-price-track-server.herokuapp.com"
basePath: "/api"
schemes:
- "https"
paths:
  /recipes:
    get:
      tags:
      - "recipes"
      summary: "Gets all recipes managed by Auction Price Tracker"
      description: ""
      operationId: "getRecipes"
      produces:
      - "application/json"
      responses:
        200:
          description: "Operation successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Recipe"
            example:
            - isCustom: true
              professions:
                - alchemy
                - inscription
              _id: 5bad6b59dcf0e92f30d04312
              reagents:
                - _id: 5bad6b59dcf0e92f30d04319
                  blizzardId: 152510
                  quantity: 1
                  name: Anchor Weed
                  name_fr: Ancoracée
                - _id: 5bad6b59dcf0e92f30d04318
                  blizzardId: 152507
                  quantity: 1
                  name: Akunda's Bite
                  name_fr: Mâche d’Akunda
                - _id: 5bad6b59dcf0e92f30d04317
                  blizzardId: 152511
                  quantity: 1
                  name: Sea Stalk
                  name_fr: Brin-de-mer
                - _id: 5bad6b59dcf0e92f30d04316
                  blizzardId: 152508
                  quantity: 1
                  name: Winter's Kiss
                  name_fr: Bise-d’hiver
                - _id: 5bad6b59dcf0e92f30d04315
                  blizzardId: 152505
                  quantity: 1
                  name: Riverbud
                  name_fr: Rivebulbe
                - _id: 5bad6b59dcf0e92f30d04314
                  blizzardId: 152509
                  quantity: 1
                  name: Siren's Pollen
                  name_fr: Pollen de sirène
                - _id: 5bad6b59dcf0e92f30d04313
                  blizzardId: 152506
                  quantity: 1
                  name: Star Moss
                  name_fr: Mousse étoilée
              __v: 0
            - isCustom: false
              professions:
                - alchemy
              _id: 5bad6b59dcf0e92f30d0431b
              type: flask
              craft:
                _id: 5bad6b59dcf0e92f30d0431c
                blizzardId: 152641
                quantity: 1
                name: Flask of the Undertow
                name_fr: Flacon du ressac
              reagents:
                - _id: 5bad6b59dcf0e92f30d0431f
                  blizzardId: 152510
                  quantity: 5
                  name: Anchor Weed
                  name_fr: Ancoracée
                - _id: 5bad6b59dcf0e92f30d0431e
                  blizzardId: 152507
                  quantity: 10
                  name: Akunda's Bite
                  name_fr: Mâche d’Akunda
                - _id: 5bad6b59dcf0e92f30d0431d
                  blizzardId: 152509
                  quantity: 15
                  name: Siren's Pollen
                  name_fr: Pollen de sirène
              __v: 0
        500:
          description: "Server broken"
          schema:
            type: "object"
            properties:
              message:
                type: string
                example: "Unfortunate things happened"
  /items:
    get:
      tags:
      - "items"
      summary: "Gets all items managed by Auction Price Tracker"
      operationId: "getItems"
      produces:
      - "application/json"
      responses:
        200:
          description: "Operation successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Item"
            example:
            - _id: 5bad6b58dcf0e92f30d0430b
              blizzardId: 152510
              name: Anchor Weed
              name_fr: Ancoracée
              __v: 0
            - _id: 5bad6b58dcf0e92f30d0430c
              blizzardId: 152507
              name: Akunda's Bite
              name_fr: Mâche d’Akunda
              __v: 0
        500:
          description: "Server broken"
          schema:
            type: "object"
            properties:
              message:
                type: string
                example: "Unfortunate things happened"
  /realms:
    get:
      tags:
      - "realms"
      summary: "Gets all realms managed by Auction Price Tracker"
      description: ""
      operationId: "getRealms"
      produces:
      - "application/json"
      responses:
        200:
          description: "Operation successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Realm"
            example:
            - _id: 5b82db8eaf83190564444808
              value: arakarahm
              label: Arak-arahm
              __v: 0
            - _id: 5b82db8eaf83190564444809
              value: arathi
              label: Arathi
              __v: 0
            - _id: 5b82db8eaf8319056444480a
              value: archimonde
              label: Archimonde
              __v: 0

        500:
          description: "Server broken"
          schema:
            type: "object"
            properties:
              message:
                type: string
                example: "Unfortunate things happened"
  /initdb/realms:
    post:
      tags:
      - "initdb"
      summary: "Clean and initialize the realm collection of the Auction Price Tracker's database"
      operationId: "initRealms"
      produces:
      - "application/json"
      responses:
        200:
          description: "Operation successful"
          schema:
            type: "object"
            properties:
              message:
                type: string
                example: "Initialization of realms finished successfully"
        500:
          description: "Server broken"
          schema:
            type: "object"
            properties:
              message:
                type: string
                example: "Unfortunate things happened"
  /initdb/recipes:
    post:
      tags:
      - "initdb"
      summary: "Initialize the recipe and item collections of the Auction Price Tracker's database"
      parameters:
        - name: cleanitemcollection
          in: query
          description: clean the item collection ?
          type: boolean
      operationId: "initRecipes"
      produces:
      - "application/json"
      responses:
        200:
          description: "Operation successful"
          schema:
            type: "object"
            properties:
              message:
                type: string
                example: "Initialization of recipes finished successfully"
        500:
          description: "Server broken"
          schema:
            type: "object"
            properties:
              message:
                type: string
                example: "Unfortunate things happened"
definitions:
  Item:
    type: "object"
    properties:
      _id:
        type: "string"
      blizzardId:
        type: "integer"
      name:
        type: "string"
      name_fr:
        type: "string"
      __v:
        type: "integer"
  Realm:
    type: "object"
    properties:
      _id:
        type: "string"
      value:
        type: "string"
      label:
        type: "string"
      __v:
        type: "integer"
  Recipe:
    type: "object"
    properties:
      _id:
        type: "string"
      isCustom:
        type: "boolean"
      professions:
        type: "array"
        items:
          type: "string"
          enum:
            - "alchemy"
            - "blacksmithing"
            - "enchant"
            - "engineering"
            - "herbalism"
            - "inscription"
            - "jewelcrafting"
            - "leatherworking"
            - "mining"
            - "skinning"
            - "tailoring"
            - "cooking"
      type:
        type: "string"
        enum:
          - "flask"
          - "potion"
          - "ring"
          - "weapon"
          - "gem"
          - "war scroll"
          - "vantus"
          - "tome"
      craft:
        type: "object"
        properties:
          _id:
            type: "string"
          blizzardId:
            type: "integer"
          quantity:
            type: "integer"
          name:
            type: "string"
          name_fr:
            type: "string"
      reagents:
        type: "array"
        items:
          type: "object"
          properties:
            _id:
              type: "string"
            blizzardId:
              type: "integer"
            quantity:
              type: "integer"
            name:
              type: "string"
            name_fr:
              type: "string"
      __v:
        type: "integer"
